# Generated by Django 3.1.4 on 2021-10-21 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Admin'), (9, 'BDM MANAGER'), (2, 'Recruiter Manager'), (3, 'Recruiter')], default=3, null=True),
        ),
        migrations.CreateModel(
            name='UserCountries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('country_code', models.CharField(max_length=255, null=True)),
                ('country_name', models.CharField(max_length=255, null=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'users_countries',
                'verbose_name_plural': 'users_countries',
                'db_table': 'users_countries',
            },
        ),
    ]
