# Generated by Django 3.1.4 on 2021-10-22 08:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211021_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('country_code', models.CharField(max_length=255, null=True)),
                ('country_name', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'countries',
                'verbose_name_plural': 'countries',
                'db_table': 'countries',
            },
        ),
        migrations.RemoveField(
            model_name='usercountries',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='usercountries',
            name='country_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.countries'),
        ),
    ]
