# Generated by Django 3.1.4 on 2021-11-01 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211022_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercountries',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercountries',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercountries_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercountries',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usercountries',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercountries_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
