# Generated by Django 3.1.4 on 2022-03-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211101_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='display_level',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
