# Generated by Django 3.1.4 on 2022-03-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_countries_display_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='display_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
