# Generated by Django 3.1.4 on 2022-12-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220323_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_user',
            field=models.CharField(blank=True, max_length=255, verbose_name='external user'),
        ),
    ]
