# Generated by Django 3.1.4 on 2021-01-13 10:40

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jobdescriptions.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobSubmissionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recruiter_email', models.CharField(max_length=255, null=True)),
                ('assignee_name', models.CharField(max_length=255, null=True)),
                ('assignee_email', models.CharField(max_length=255, null=True)),
                ('remarks', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidates')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobsubmissionmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('recruiter_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_recruiter', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobsubmissionmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Description Submission',
                'verbose_name_plural': 'Submission List',
                'db_table': 'job_description_submission',
            },
        ),
        migrations.CreateModel(
            name='jobModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('job_id', models.CharField(default=jobdescriptions.models.create_id, max_length=255, null=True)),
                ('end_client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, max_length=255, null=True)),
                ('industry_experience', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('nice_to_have_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('job_pdf', models.FileField(null=True, upload_to='jds/')),
                ('visa_type', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_requests', models.IntegerField(blank=True, null=True)),
                ('roles_and_responsibilities', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('years_of_experience', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('key_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('education_qualificaion', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('key_fields', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('projected_revenue', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('revenue_frequqney', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clientmodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('default_assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_assignee', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'db_table': 'osms_job_description',
                'get_latest_by': ['id'],
            },
        ),
        migrations.CreateModel(
            name='jobAssingmentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('primary_recruiter_email', models.CharField(max_length=255, null=True)),
                ('secondary_recruiter_email', models.CharField(blank=True, max_length=255, null=True)),
                ('assignee_name', models.CharField(max_length=255, null=True)),
                ('assignee_email', models.CharField(max_length=255, null=True)),
                ('remarks', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobassingmentmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobdescriptions.jobmodel')),
                ('primary_recruiter_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinged_primary_recruiter', to=settings.AUTH_USER_MODEL)),
                ('secondary_recruiter_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinged_secondary_recruiter', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobassingmentmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Description Assingment',
                'verbose_name_plural': 'Assingment List',
                'db_table': 'job_description_assingment',
            },
        ),
    ]
