# Generated by Django 3.1.4 on 2021-01-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0002_auto_20210119_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='priority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
