# Generated by Django 3.1.4 on 2021-01-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0003_auto_20210122_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='Rate',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='max_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='min_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='industry_experience',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='priority',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='projected_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='years_of_experience',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
