# Generated by Django 3.1.4 on 2021-01-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0004_auto_20210122_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='salary',
            new_name='max_salary',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
