# Generated by Django 3.1.4 on 2021-01-29 06:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0005_auto_20210125_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='contract_type',
            new_name='employment_type',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='years_of_experience',
            new_name='max_years_of_experience',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='employment_type_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='min_years_of_experience',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='industry_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
