# Generated by Django 3.1.4 on 2021-05-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0006_auto_20210129_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='client_max_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='client_min_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
