# Generated by Django 3.1.4 on 2021-05-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0007_auto_20210520_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='client_max_rate',
            new_name='max_client_rate',
        ),
        migrations.RenameField(
            model_name='jobmodel',
            old_name='client_min_rate',
            new_name='min_client_rate',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='job_posted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='job_recruiter_pdf',
            field=models.FileField(null=True, upload_to='jds-recruiters/'),
        ),
    ]
