# Generated by Django 3.1.4 on 2021-09-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0008_auto_20210528_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
