# Generated by Django 3.1.4 on 2022-03-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0009_jobmodel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassingmentmodel',
            name='time_window',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
