# Generated by Django 3.1.4 on 2022-06-06 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0011_jobnotesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobnotesmodel',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobdescriptions.jobmodel'),
        ),
    ]
