# Generated by Django 3.1.4 on 2022-06-07 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0013_auto_20220607_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobnotesmodel',
            old_name='job_idd',
            new_name='job_id',
        ),
    ]
