# Generated by Django 3.1.4 on 2022-11-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0014_auto_20220607_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
