# Generated by Django 3.1.4 on 2022-12-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0015_jobmodel_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='mode_of_interview',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='mode_of_work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='notice_period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='number_of_opening',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
