# Generated by Django 3.1.4 on 2022-12-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0016_auto_20221215_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='mandate_skills',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
