# Generated by Django 3.1.4 on 2022-12-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0017_jobmodel_mandate_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='mandate_skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
