# Generated by Django 3.1.4 on 2023-01-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0018_auto_20221218_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='is_deleted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
