# Generated by Django 3.1.4 on 2023-01-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0019_jobmodel_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='manual_update',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
