# Generated by Django 3.1.4 on 2023-02-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0020_jobmodel_manual_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassingmentmodel',
            name='assignment_date',
            field=models.DateTimeField(null=True),
        ),
    ]
