# Generated by Django 3.1.4 on 2023-08-01 13:01

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jobdescriptions.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientmodel_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobdescriptions', '0021_jobassingmentmodel_assignment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModelBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('job_id', models.CharField(default=jobdescriptions.models.create_id, max_length=255, null=True)),
                ('end_client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.BooleanField(blank=True, null=True)),
                ('industry_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('nice_to_have_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('job_pdf', models.FileField(null=True, upload_to='jds/')),
                ('job_recruiter_pdf', models.FileField(null=True, upload_to='jds-recruiters/')),
                ('visa_type', models.CharField(blank=True, max_length=255, null=True)),
                ('no_of_requests', models.IntegerField(blank=True, null=True)),
                ('roles_and_responsibilities', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('min_years_of_experience', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('max_years_of_experience', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('key_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('education_qualificaion', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('contract_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('max_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('min_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('min_client_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('max_client_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('key_fields', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_period', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_of_interview', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_opening', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_of_work', models.CharField(blank=True, max_length=255, null=True)),
                ('mandate_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.IntegerField(blank=True, null=True)),
                ('manual_update', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('projected_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('revenue_frequency', models.CharField(blank=True, max_length=255, null=True)),
                ('job_posted_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clientmodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobmodelbackup_created_by', to=settings.AUTH_USER_MODEL)),
                ('default_assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_model_backups', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobmodelbackup_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Description Backup',
                'verbose_name_plural': 'Job Description Backups',
                'db_table': 'osms_job_description_backup',
                'get_latest_by': ['id'],
            },
        ),
    ]
