# Generated by Django 3.1.4 on 2023-08-01 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0022_jobmodelbackup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobmodelbackup',
            options={'get_latest_by': ['id'], 'verbose_name': 'Job Description Delete Backup', 'verbose_name_plural': 'Job Description Delete Backups'},
        ),
        migrations.AlterModelTable(
            name='jobmodelbackup',
            table='osms_job_description_delete_backup',
        ),
    ]
