version: '3'
services:
  redis:
    image: redis
    expose:
      - '6379'
  web:
    build: 
       context: .
       dockerfile: Dockerfile.dev
    volumes:
      - ./website:/code/website
    ports:
      - "8000:8000"
    environment:
      - DJANGO_READ_DOT_ENV_FILE=${DJANGO_READ_DOT_ENV_FILE}
      - DEBUG=${DEBUG}
      - DB_DEFAULT_NAME=${DB_DEFAULT_NAME}
      - DB_DEFAULT_USER=${DB_DEFAULT_USER}
      - DB_DEFAULT_PASSWORD=${DB_DEFAULT_PASSWORD}
      - DB_DEFAULT_HOST=${DB_DEFAULT_HOST}
      - DB_DEFAULT_PORT=${DB_DEFAULT_PORT}
      - DB_CLIENT_NAME=${DB_CLIENT_NAME}
      - DB_WEB_NAME=${DB_WEB_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
      - AUTH_TOKEN_SECRET=${AUTH_TOKEN_SECRET}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - SECRET_KEY=${SECRET_KEY}
      - STRIPE_PUBLISHABLE_ONTARIO=${STRIPE_PUBLISHABLE_ONTARIO}
      - STRIPE_PUBLISHABLE_ALBERTA=${STRIPE_PUBLISHABLE_ALBERTA}
      - STRIPE_PUBLISHABLE_NATIONWIDE=${STRIPE_PUBLISHABLE_NATIONWIDE}
      - STRIPE_PUBLISHABLE_BRITISH_COLUMBIA=${STRIPE_PUBLISHABLE_BRITISH_COLUMBIA}
      - STRIPE_PUBLISHABLE_ILLINOIS=${STRIPE_PUBLISHABLE_ILLINOIS}
      - STRIPE_PUBLISHABLE_INVALID=${STRIPE_PUBLISHABLE_INVALID}
      - STRIPE_API_KEY_ONTARIO=${STRIPE_API_KEY_ONTARIO}
      - STRIPE_API_KEY_ALBERTA=${STRIPE_API_KEY_ALBERTA}
      - STRIPE_API_KEY_NATIONWIDE=${STRIPE_API_KEY_NATIONWIDE}
      - STRIPE_API_KEY_BRITISH_COLUMBIA=${STRIPE_API_KEY_BRITISH_COLUMBIA}
      - STRIPE_API_KEY_ILLINOIS=${STRIPE_API_KEY_ILLINOIS}
      - STRIPE_API_KEY_INVALID=${STRIPE_API_KEY_INVALID}
      - DJANGO_DATABASE_URL=${DJANGO_DATABASE_URL}
      - CLIENT_DATABASE_URL=${CLIENT_DATABASE_URL}
      - CONNECT_DATABASE_URL=${CONNECT_DATABASE_URL}
      - WEB_DATABASE_URL=${WEB_DATABASE_URL}
      - TRULOCAL_ENVIRONMENT=${TRULOCAL_ENVIRONMENT}
      - ENDPOINTS_URL=${ENDPOINTS_URL}
      - SEGMENT_DISABLED=${SEGMENT_DISABLED}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis 
