FROM trulocalplatform/docker-python-nodejs
ENV PYTHONUNBUFFERED 1
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN apt-get update
RUN apt-get install -y gettext
RUN mkdir /code
WORKDIR /code
COPY . /code/
RUN pip install -r requirements.txt --prefer-binary
RUN npm install
RUN mkdir /code/staticfiles
CMD ["sh","-c","npm run build && python manage.py collectstatic --no-input && python manage.py compilemessages && python manage.py runserver 0.0.0.0:8000"]