"""
Django settings for staffingapp project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
import logging.config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

REDIS_HOST = 'localhost'
REDIS_PORT = 6379

# Add these new lines
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'assets')
]

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.DefaultStorageFinder',
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ff%7t#-#_&=xmfhza44&%a(4n5(3m-qus$i_==#@$0&dj#!3&_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

"""
ALLOWED_HOSTS = [
    '207.180.198.237',
    '127.0.0.1',
    'localhost',
	'http://localhost:4200'
]
"""
ALLOWED_HOSTS = ['*']

ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = '/?verification=1'
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/?verification=1'

SITE_ID = 1

ACCOUNT_USER_EMAIL_FIELD = 'email'
ACCOUNT_LOGOUT_ON_GET = True

AUTH_USER_MODEL = 'users.User'

FILE_UPLOAD_MAX_MEMORY_SIZE = 10000000

REST_AUTH_SERIALIZERS = {
    "USER_DETAILS_SERIALIZER": "users.serializers.UserRegisterSerializer",
}
REST_AUTH_REGISTER_SERIALIZERS = {
    "REGISTER_SERIALIZER": "users.serializers.UserRegisterSerializer",
}

# Application definition
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    # 'DEFAULT_PAGINATION_CLASS': 'staffingapp.pagination.HeaderLimitOffsetPagination',
    'PAGE_SIZE': 1000000
}

SWAGGER_SETTINGS = {
    'SHOW_REQUEST_HEADERS': True,
    "SUPPORTED_SUBMIT_METHOD": ['get', 'post', 'put', 'delete', ],
    'USE_SESSION_AUTH': False,
    "LOGIN_URL": "/",
    "LOGOUT_URL": "/",
    'SECURITY_DEFINITIONS': {
        'api_key': {
            'type': 'basic',
            'description': 'Personal API Key authorization',
            'name': 'Authorization',
            'in': 'header',
        }
    },
    'APIS_SORTER': 'alpha',
    "SHOW_REQUEST_HEADERS": True,
    "VALIDATOR_URL": None,
    'api_key': 'cea4bd55bdcf8ab18cb4e9b19f7236acc241a5ac',  # An API key

}

CKEDITOR_UPLOAD_PATH = os.path.join(BASE_DIR, 'uploads')
CKEDITOR_RESTRICT_BY_USER = True

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Advanced',
        'width': 758,
        'height': 300,
        'autoParagraph': False
    },
}

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'candidates',
    'clients',
    'jobdescriptions',
    'interviewers',
    'interviews',
    'vendors',
    'users',
    'candidatesdocumentrepositery',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework.authtoken',
    'rest_framework_swagger',
    'corsheaders',
    'reports',
    'website',
    'schedulers',
    'django_filters',
    'celery',
    'dbbackup',
    'django_celery_beat'
]

CREDENTIALS_FILE = os.path.join(BASE_DIR, 'client_id.json')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'osms.opallios@gmail.com'
EMAIL_HOST_PASSWORD = 'Osms@123'

ZOOM_API_KEY = 'lWuC-FosTCa3njZ0oyfpNg'
ZOOM_API_SECRET = 'jns5o1B3Fjvzbb84RraYZbTgCZ0rLOFeVks0'
ZOOM_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOm51bGwsImlzcyI6ImxXdUMtRm9zVENhM25qWjBveWZwTmciLCJleHAiOjM4MDI1MDc1NjAsImlhdCI6MTU5MzUxMzUwMn0.Q-X8VKH3OZz3HlGPURQSiA8-MVtYL1hhJXpKQoVD-6E'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'staffingapp.urls'
CORS_ORIGIN_ALLOW_ALL = True

CORS_ORIGIN_WHITELIST = [
    'http://localhost:4200',
    'http://localhost:8000',
    'http://127.0.0.1:9000'
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'static', 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'staffingapp.wsgi.application'

DBBACKUP_STORAGE = "django.core.files.storage.FileSystemStorage"
DBBACKUP_STORAGE_OPTIONS = {
    "location": os.path.join(BASE_DIR, 'backups')
}

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'staffingapp_dev',
        'USER': 'Nareshkhuriwal',
        'PASSWORD': 'Naresh@2252',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {'charset': 'utf8mb4',
            "init_command": "SET foreign_key_checks = 0;"
        },
        # 'OPTIONS': {
        #    'read_default_file': '../my.cnf',
        #    'init_command': 'SET default_storage_engine=INNODB',
        # },
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S' 

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = False

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
LOGIN_URL = 'rest_framework:login'
LOGOUT_URL = 'rest_framework:logout'

GLOBAL_ROLE = {
    'ADMIN': 'ADMIN',
    'BDMMANAGER': 'BDM MANAGER',
    'RECRUITER': 'RECRUITER',
    'RECRUITERMANAGER': 'RECRUITER MANAGER',
}

SUBMISSION_MAIL = "recsub@opallios.com"

# Celery Configuration Options
# CELERY_TIMEZONE = "UTC"
CELERY_TIMEZONE = 'Asia/Kolkata'

# CELERY_TASK_TRACK_STARTED = True
# CELERY_TASK_TIME_LIMIT = 10  # no task should run for more than 10 seconds. Heroku force kills kills after 10 seconds.
# CELERY_BROKER_URL = env('REDIS_URL', default='redis://localhost:6379')
# CELERY_RESULT_BACKEND = env('REDIS_URL', default='redis://localhost:6379')
# CELERY_CACHE_BACKEND = env('REDIS_URL', default='redis://localhost:6379')
BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_CACHE_BACKEND = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
