# Generated by Django 3.1.4 on 2021-03-01 06:15

import candidatesdocumentrepositery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatesdocumentrepositery', '0002_auto_20210122_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesrepositerymodel',
            name='educational_document',
            field=models.FileField(blank=True, null=True, upload_to=candidatesdocumentrepositery.models.content_educational_document),
        ),
        migrations.AddField(
            model_name='candidatesrepositerymodel',
            name='i94_document',
            field=models.FileField(blank=True, null=True, upload_to=candidatesdocumentrepositery.models.content_i94_document),
        ),
        migrations.AddField(
            model_name='candidatesrepositerymodel',
            name='visa_copy',
            field=models.FileField(blank=True, null=True, upload_to=candidatesdocumentrepositery.models.content_visa_copy),
        ),
    ]
