# Generated by Django 3.1.4 on 2021-12-17 19:18

import candidatesdocumentrepositery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidatesdocumentrepositery', '0003_auto_20210301_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesrepositerymodel',
            name='additional_qualification_doc',
            field=models.FileField(blank=True, null=True, upload_to=candidatesdocumentrepositery.models.content_additional_qualification_doc),
        ),
        migrations.AddField(
            model_name='candidatesrepositerymodel',
            name='certification_doc',
            field=models.FileField(blank=True, null=True, upload_to=candidatesdocumentrepositery.models.content_certification_doc),
        ),
    ]
