# Generated by Django 3.1.4 on 2021-01-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='total_employee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
