# Generated by Django 3.1.4 on 2021-09-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210119_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
