# Generated by Django 3.1.4 on 2021-01-13 10:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
        ('interviewers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_email', models.CharField(max_length=255, null=True, unique=True)),
                ('secondary_email', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_phone_number', models.CharField(max_length=255, null=True)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_1', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_2', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('visa', models.CharField(blank=True, max_length=255, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('total_experience', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('reason_for_job_change', models.CharField(blank=True, max_length=255, null=True)),
                ('rtr_done', models.CharField(blank=True, max_length=255, null=True)),
                ('willing_to_work_on_our_w2', models.CharField(blank=True, max_length=255, null=True)),
                ('open_for_relocation', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.IntegerField(blank=True, default=0, null=True)),
                ('total_experience_in_usa', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('any_offer_in_hand', models.CharField(blank=True, max_length=255, null=True)),
                ('resume', models.FileField(null=True, upload_to='resumes/')),
                ('remarks', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('recruiter_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates_created_by', to=settings.AUTH_USER_MODEL)),
                ('designations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='interviewers.designationmodel')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'osms_candidates',
            },
        ),
        migrations.CreateModel(
            name='emailTemplateModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('template_name', models.CharField(max_length=255, null=True, unique=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('body', models.TextField(null=True)),
                ('signature', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailtemplatemodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailtemplatemodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'db_table': 'osms_email_templates',
            },
        ),
        migrations.CreateModel(
            name='searchTermModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('search_term', models.TextField(max_length=255, null=True)),
                ('search_date', models.CharField(max_length=255, null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searchtermmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searchtermmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidates_search_terms',
            },
        ),
        migrations.CreateModel(
            name='rtrModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('rate', models.CharField(max_length=255, null=True)),
                ('consultant_full_legal_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('last_4_ssn', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('rtr_doc', models.FileField(null=True, upload_to='rtrs/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidates')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtrmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtrmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RTR',
                'verbose_name_plural': 'RTR',
                'db_table': 'candidates_rtr',
            },
        ),
        migrations.CreateModel(
            name='rtrmailModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email_from', models.CharField(max_length=255, null=True)),
                ('email_to', models.CharField(max_length=255, null=True)),
                ('cc_email', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('body', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtrmailmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtrmailmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RTR Mail',
                'db_table': 'rtr_mails',
            },
        ),
        migrations.CreateModel(
            name='placementCardModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reminder_date', models.DateField(null=True)),
                ('payment_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('recruiter_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidates')),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clientmodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placementcardmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placementcardmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Placement Card',
                'verbose_name_plural': 'Placement Cards',
                'db_table': 'candidates_placement_cards',
            },
        ),
        migrations.CreateModel(
            name='mailModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tag', models.CharField(max_length=255, null=True)),
                ('email_from', models.CharField(max_length=255, null=True)),
                ('email_to', models.TextField(null=True)),
                ('cc_email', models.CharField(blank=True, max_length=255, null=True)),
                ('bcc_email', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='candidates-attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.emailtemplatemodel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mail',
                'db_table': 'candidates_mail',
            },
        ),
        migrations.CreateModel(
            name='importFileModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('module', models.CharField(max_length=255, null=True)),
                ('file', models.FileField(null=True, upload_to='imported-files/')),
                ('data_fields', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='importfilemodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='importfilemodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'osms_imported_files',
            },
        ),
        migrations.CreateModel(
            name='candidateStageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('stage_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatestagemodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatestagemodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Stage',
                'verbose_name_plural': 'Candidate Stages',
                'db_table': 'candidates_stages',
            },
        ),
        migrations.CreateModel(
            name='candidatesSubmissionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email_from', models.CharField(max_length=255, null=True)),
                ('client_email', models.CharField(max_length=255, null=True)),
                ('email_cc', models.CharField(blank=True, max_length=255, null=True)),
                ('email_subject', models.CharField(max_length=255, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('email_attachment', models.FileField(null=True, upload_to='submission-attachments/')),
                ('recruiter_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidates')),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clientmodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatessubmissionmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatessubmissionmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Candidates Submissions',
                'db_table': 'candidates_submission',
            },
        ),
        migrations.AddField(
            model_name='candidates',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidatestagemodel'),
        ),
        migrations.AddField(
            model_name='candidates',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='activityStatusModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('activity_status', models.CharField(max_length=255, null=True)),
                ('notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidates')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitystatusmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activitystatusmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Status',
                'verbose_name_plural': 'Candidates Activity Status',
                'db_table': 'candidates_activity_status',
            },
        ),
    ]
