# Generated by Django 3.1.4 on 2021-01-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatestagemodel',
            name='created_at',
        ),
    ]
