# Generated by Django 3.1.4 on 2021-01-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_remove_candidatestagemodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestagemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
