# Generated by Django 3.1.4 on 2021-01-13 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        ('candidates', '0003_candidatestagemodel_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmodel',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='mailmodel',
            name='template',
        ),
        migrations.AddField(
            model_name='mailmodel',
            name='candidate_attachment',
            field=models.FileField(blank=True, null=True, upload_to='candidate-mail-attachments/'),
        ),
        migrations.AddField(
            model_name='mailmodel',
            name='candidate_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.emailtemplatemodel'),
        ),
        migrations.AddField(
            model_name='mailmodel',
            name='vendor_attachment',
            field=models.FileField(blank=True, null=True, upload_to='vendors-mail-attachments/'),
        ),
        migrations.AddField(
            model_name='mailmodel',
            name='vendor_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendoremailtemplatemodel'),
        ),
    ]
