# Generated by Django 3.1.4 on 2021-01-14 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0001_initial'),
        ('candidates', '0004_auto_20210113_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='job_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobdescriptions.jobmodel'),
        ),
    ]
