# Generated by Django 3.1.4 on 2021-01-22 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0001_initial'),
        ('candidates', '0005_candidates_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='designations',
        ),
        migrations.AddField(
            model_name='candidates',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation', to='interviewers.designationmodel'),
        ),
    ]
