# Generated by Django 3.1.4 on 2021-01-22 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0004_auto_20210122_1123'),
        ('candidates', '0006_auto_20210122_0605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidates',
            name='rate',
        ),
        migrations.AddField(
            model_name='candidates',
            name='max_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='min_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='job_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobdescriptions.jobmodel'),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='total_experience',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='total_experience_in_usa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
