# Generated by Django 3.1.4 on 2021-02-10 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobdescriptions', '0006_auto_20210129_0622'),
        ('candidates', '0008_auto_20210125_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitystatusmodel',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobdescriptions.jobmodel'),
        ),
        migrations.AddField(
            model_name='placementcardmodel',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobdescriptions.jobmodel'),
        ),
        migrations.AddField(
            model_name='rtrmodel',
            name='job_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobdescriptions.jobmodel'),
        ),
        migrations.CreateModel(
            name='candidatesJobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('submission_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.candidates')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatesjobdescription_created_by', to=settings.AUTH_USER_MODEL)),
                ('job_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobdescriptions.jobmodel')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.candidatestagemodel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatesjobdescription_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'candidates_jobs_stages',
            },
        ),
    ]
