# Generated by Django 3.1.4 on 2021-02-12 10:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobdescriptions', '0006_auto_20210129_0622'),
        ('candidates', '0009_auto_20210210_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatesjobdescription',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatesjobdescription',
            name='send_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='job_description',
        ),
        migrations.AddField(
            model_name='candidates',
            name='job_description',
            field=models.ManyToManyField(blank=True, to='jobdescriptions.jobModel'),
        ),
    ]
