# Generated by Django 3.1.4 on 2021-03-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_auto_20210212_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='employer_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='employer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='employer_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='engagement_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
