# Generated by Django 3.1.4 on 2021-11-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_auto_20210301_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesjobdescription',
            name='submission_date',
            field=models.DateField(null=True),
        ),
    ]
