# Generated by Django 3.1.4 on 2021-11-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0012_auto_20211129_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesjobdescription',
            name='send_out_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
