# Generated by Django 3.1.4 on 2021-11-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0014_auto_20211129_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatesjobdescription',
            name='send_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatesjobdescription',
            name='submission_date',
            field=models.DateField(null=True),
        ),
    ]
