# Generated by Django 3.1.4 on 2021-12-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0016_auto_20211130_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='additional_qualification',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidates',
            name='certification',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
