# Generated by Django 3.1.4 on 2022-04-01 17:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0017_auto_20211217_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='resume_raw_data',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidates',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
