# Generated by Django 3.1.4 on 2022-08-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0019_candidatestagemodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
