# Generated by Django 3.1.4 on 2022-10-12 17:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0021_candidates_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='candidateResumesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('job_title', models.CharField(max_length=255, null=True)),
                ('candidate_resume_data', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.candidates')),
            ],
            options={
                'verbose_name': 'Candidate Resumes',
                'verbose_name_plural': 'Candidate Resumes',
                'db_table': 'candidates_resumes',
            },
        ),
    ]
