# Generated by Django 3.1.4 on 2022-10-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0022_candidateresumesmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateresumesmodel',
            name='candidates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidates'),
        ),
    ]
