# Generated by Django 3.1.4 on 2023-01-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0023_auto_20221012_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestagemodel',
            name='type',
            field=models.CharField(choices=[('Internal', 'Internal'), ('External', 'External')], default='External', max_length=10),
        ),
    ]
