# Generated by Django 3.1.4 on 2023-01-11 17:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobdescriptions', '0019_jobmodel_is_deleted'),
        ('candidates', '0024_candidatestagemodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='internalCandidatesJobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('submission_date', models.DateTimeField(null=True)),
                ('send_out_date', models.DateTimeField(blank=True, null=True)),
                ('notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.candidates')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internalcandidatesjobdescription_created_by', to=settings.AUTH_USER_MODEL)),
                ('job_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobdescriptions.jobmodel')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.candidatestagemodel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internalcandidatesjobdescription_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'internal_candidates_jobs_stages',
            },
        ),
    ]
