# Generated by Django 3.1.4 on 2023-08-04 10:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobdescriptions', '0023_auto_20230801_1410'),
        ('candidates', '0025_internalcandidatesjobdescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateModelBackup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_email', models.CharField(max_length=255, null=True, unique=True)),
                ('secondary_email', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_phone_number', models.CharField(max_length=255, null=True)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_1', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_2', models.CharField(blank=True, max_length=255, null=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('min_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('max_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=255, null=True)),
                ('visa', models.CharField(blank=True, max_length=255, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('total_experience', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('reason_for_job_change', models.CharField(blank=True, max_length=255, null=True)),
                ('rtr_done', models.CharField(blank=True, max_length=255, null=True)),
                ('willing_to_work_on_our_w2', models.CharField(blank=True, max_length=255, null=True)),
                ('open_for_relocation', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.IntegerField(blank=True, default=0, null=True)),
                ('total_experience_in_usa', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('employer_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('employer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('engagement_type', models.CharField(blank=True, max_length=255, null=True)),
                ('any_offer_in_hand', models.CharField(blank=True, max_length=255, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_raw_data', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('remarks', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('certification', models.CharField(max_length=255, null=True)),
                ('additional_qualification', models.CharField(max_length=255, null=True)),
                ('recruiter_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatemodelbackup_created_by', to=settings.AUTH_USER_MODEL)),
                ('job_description', models.ManyToManyField(blank=True, to='jobdescriptions.jobModel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatemodelbackup_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidate Backup',
                'verbose_name_plural': 'Candidates Backup',
                'db_table': 'osms_candidates_backup',
            },
        ),
    ]
