# Generated by Django 3.1.4 on 2023-08-07 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interviewers', '0001_initial'),
        ('candidates', '0026_candidatemodelbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemodelbackup',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation_backup', to='interviewers.designationmodel'),
        ),
        migrations.AddField(
            model_name='candidatemodelbackup',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidatestagemodel'),
        ),
    ]
