# Generated by Django 3.1.4 on 2022-02-07 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLettersModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('candidate_name', models.CharField(max_length=255, null=True)),
                ('years_of_exp', models.CharField(max_length=255, null=True)),
                ('skill_set', models.CharField(max_length=255, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, max_length=255, null=True)),
                ('percentage', models.CharField(blank=True, max_length=255, null=True)),
                ('university_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pan_no', models.CharField(blank=True, max_length=255, null=True)),
                ('qualification_completion', models.CharField(max_length=255, null=True)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('tentative_joining_date', models.IntegerField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_location', models.CharField(blank=True, max_length=255, null=True)),
                ('ecms_id', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_ctc', models.CharField(blank=True, max_length=255, null=True)),
                ('client_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('joining_date', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('bgc_steps', models.CharField(blank=True, max_length=255, null=True)),
                ('expected_working_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('laptop_provided', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_information_sheet', models.CharField(blank=True, max_length=255, null=True)),
                ('resume', models.CharField(blank=True, max_length=255, null=True)),
                ('provident_fund', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerlettersmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offerlettersmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OfferLetters',
                'verbose_name_plural': 'OfferLetters List',
                'db_table': 'osms_offerletters',
            },
        ),
    ]
