# Generated by Django 3.1.4 on 2022-02-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerletters', '0002_auto_20220207_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlettersmodel',
            name='provident_fund',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='offerlettersmodel',
            name='tentative_joining_date',
            field=models.DateTimeField(null=True),
        ),
    ]
