# Generated by Django 3.1.4 on 2022-02-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerletters', '0003_auto_20220209_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlettersmodel',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='offerlettersmodel',
            name='expected_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='offerlettersmodel',
            name='joining_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='offerlettersmodel',
            name='tentative_joining_date',
            field=models.DateField(null=True),
        ),
    ]
