# Generated by Django 3.1.4 on 2022-02-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerletters', '0004_auto_20220209_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlettersmodel',
            name='candidate_information_sheet',
            field=models.FileField(null=True, upload_to='offerletter_candidate_information_sheet/'),
        ),
        migrations.AlterField(
            model_name='offerlettersmodel',
            name='resume',
            field=models.FileField(null=True, upload_to='offerletter_candidate_resume-attachments/'),
        ),
    ]
