# Generated by Django 3.1.4 on 2022-02-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offerletters', '0005_auto_20220209_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerlettersmodel',
            name='offer_letter_pdf',
            field=models.FileField(null=True, upload_to='offer_letters/'),
        ),
    ]
