# Generated by Django 3.1.4 on 2022-02-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerletters', '0006_offerlettersmodel_offer_letter_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerlettersmodel',
            name='candidate_information_sheet',
        ),
    ]
