# Generated by Django 3.1.4 on 2021-01-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_emailconfigurationmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfigurationmodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailconfigurationmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
