# Generated by Django 3.1.4 on 2021-08-23 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0003_auto_20210125_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorListModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('list_name', models.CharField(blank=True, max_length=255, null=True)),
                ('list_size', models.CharField(blank=True, max_length=255, null=True)),
                ('list_description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorlistmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('template_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendoremailtemplatemodel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorlistmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor_lists',
            },
        ),
        migrations.CreateModel(
            name='VendorListDataModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorlistdatamodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorlistmodel')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendoremailtemplatemodel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendorlistdatamodel_updated_by', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendormodel')),
            ],
            options={
                'db_table': 'vendor_list_data',
            },
        ),
    ]
