# Generated by Django 3.1.4 on 2021-08-23 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_vendorlistdatamodel_vendorlistmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorlistdatamodel',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorlistmodel'),
        ),
        migrations.AlterField(
            model_name='vendorlistdatamodel',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendoremailtemplatemodel'),
        ),
        migrations.AlterField(
            model_name='vendorlistdatamodel',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendormodel'),
        ),
        migrations.AlterField(
            model_name='vendorlistmodel',
            name='template_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendoremailtemplatemodel'),
        ),
    ]
