# Generated by Django 3.1.4 on 2021-08-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20210823_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlistmodel',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendorlistmodel',
            name='list_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
