# Generated by Django 3.1.4 on 2021-09-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_auto_20210824_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlistdatamodel',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorlistdatamodel',
            name='email_subject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorlistdatamodel',
            name='email_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
