# Generated by Django 3.1.4 on 2021-09-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_maileventsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendormodel',
            name='contact_person_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendormodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
