# Generated by Django 3.1.4 on 2021-09-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0010_emailconfigurationmodel_send_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfigurationmodel',
            name='email_cc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
