# Generated by Django 3.1.4 on 2021-10-28 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0011_emailconfigurationmodel_email_cc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('email_from', models.CharField(blank=True, max_length=255, null=True)),
                ('email_to', models.CharField(blank=True, max_length=255, null=True)),
                ('email_cc', models.CharField(max_length=255)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'email_queues',
                'verbose_name_plural': 'email_queues',
                'db_table': 'email_queue',
            },
        ),
    ]
