# Generated by Django 3.1.4 on 2021-10-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0012_emailmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
