# Generated by Django 3.1.4 on 2021-10-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0013_auto_20211028_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
