# Generated by Django 3.1.4 on 2021-10-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0014_emailmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emailmodel',
            name='email_cc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
