# Generated by Django 3.1.4 on 2022-08-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0015_auto_20211029_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorlistdatamodel',
            name='vendor',
        ),
        migrations.AddField(
            model_name='vendorlistdatamodel',
            name='record_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendorlistmodel',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='campaign_data/'),
        ),
    ]
