# Generated by Django 3.1.4 on 2022-08-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0016_auto_20220809_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlistmodel',
            name='data_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
