# Generated by Django 3.1.4 on 2022-09-14 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0002_campaignlistuploaddatamodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=255)),
                ('field_size', models.CharField(max_length=255)),
                ('field_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('field_scope', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customfieldsmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customfieldsmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_fields',
            },
        ),
    ]
