# Generated by Django 3.1.4 on 2022-09-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_customfieldsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlistmodel',
            name='list_mapping',
            field=models.TextField(null=True),
        ),
    ]
