# Generated by Django 3.1.4 on 2021-01-13 10:41

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobdescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0001_initial'),
        ('interviewers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('zoom_username', models.EmailField(max_length=254, null=True)),
                ('zoom_password', models.CharField(max_length=1000, null=True)),
                ('zoom_api_key', models.CharField(max_length=1000, null=True)),
                ('zoom_api_secret', models.CharField(max_length=1000, null=True)),
                ('zoom_token', models.TextField(null=True)),
                ('meeting_topic', models.CharField(max_length=1000, null=True)),
                ('meeting_agenda', models.TextField(null=True)),
                ('meeting_time', models.DateField(null=True)),
                ('meeting_time_zone', models.CharField(max_length=1000, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zoomobject_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zoomobject_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='sourceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('source', models.CharField(max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourcemodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sourcemodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Mode',
                'verbose_name_plural': 'Interview Modes',
                'db_table': 'interview_source',
            },
        ),
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('condidate_email', models.EmailField(max_length=254, null=True)),
                ('from_email', models.CharField(max_length=1000, null=True)),
                ('subject', models.CharField(max_length=1000, null=True)),
                ('message', models.TextField(null=True)),
                ('resume', models.CharField(max_length=1000, null=True)),
                ('jd', models.TextField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='interviewsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time_zone', models.CharField(max_length=255, null=True)),
                ('meeting_time', models.DateField(null=True)),
                ('status', models.CharField(default='New', max_length=255)),
                ('remarks', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('recruiter_name', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidates')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewsmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('interviewer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviewers.interviewersmodel')),
                ('jd_attachment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobdescriptions.jobmodel')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.sourcemodel')),
                ('time_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviewers.timeslotsmodel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewsmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview',
                'verbose_name_plural': 'Interviews',
                'db_table': 'osms_interviews',
            },
        ),
        migrations.CreateModel(
            name='feedbackModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('interview_date', models.DateField(null=True)),
                ('duration', models.CharField(max_length=255, null=True)),
                ('forwarded', models.CharField(max_length=255, null=True)),
                ('mail_from', models.CharField(max_length=255, null=True)),
                ('mail_to', models.CharField(max_length=255, null=True)),
                ('mail_subject', models.CharField(max_length=255, null=True)),
                ('mail_cc', models.CharField(blank=True, max_length=400, null=True)),
                ('feedback', ckeditor.fields.RichTextField(null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='feedback-attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidates')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('interview', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.interviewsmodel')),
                ('time_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviewers.timeslotsmodel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
                'db_table': 'osms_interviews_feedbacks',
            },
        ),
    ]
