# Generated by Django 3.1.4 on 2022-08-09 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0015_auto_20211029_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignUploadDataModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('list_name', models.CharField(max_length=255, null=True, unique=True)),
                ('list_size', models.CharField(blank=True, max_length=255, null=True)),
                ('list_description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='campaign_data/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaignuploaddatamodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('template_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.vendoremailtemplatemodel')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaignuploaddatamodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_upload_data',
            },
        ),
        migrations.CreateModel(
            name='CampaignListDataModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedulers.campaignuploaddatamodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaignlistdatamodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaignlistdatamodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_list_data',
            },
        ),
    ]
