# Generated by Django 3.1.4 on 2022-08-22 17:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedulers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendCleanRequestDataModel',
            fields=[
                ('_id', models.UUIDField(default=uuid.UUID('dcb01420-a401-413b-bc41-cfbfac599029'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('x_unique_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ts', models.CharField(blank=True, max_length=255, null=True)),
                ('msg', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sarvtes_events', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sendcleanrequestdatamodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sendcleanrequestdatamodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'send_clean_request_data',
            },
        ),
        migrations.CreateModel(
            name='sendCleanDataModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('09ce481e-3563-4234-afc9-6c7390abf85c'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('send', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered', models.CharField(blank=True, max_length=255, null=True)),
                ('marked_as_spam', models.CharField(blank=True, max_length=255, null=True)),
                ('soft_bounced', models.CharField(blank=True, max_length=255, null=True)),
                ('hard_bounced', models.CharField(blank=True, max_length=255, null=True)),
                ('opened', models.CharField(blank=True, max_length=255, null=True)),
                ('clicked', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sendcleandatamodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sendcleandatamodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'send_clean_dashboard',
            },
        ),
    ]
