# Generated by Django 3.1.4 on 2022-08-26 12:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0003_auto_20220826_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendcleanrequestdatamodel',
            old_name='_id',
            new_name='record_id',
        ),
        migrations.AlterField(
            model_name='sendcleandatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b01f6839-223d-47e3-abfb-626e280979ee'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('423d6bad-2259-4786-adc5-459dbd2e9a37'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
