# Generated by Django 3.1.4 on 2022-08-26 13:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0004_auto_20220826_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleandatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a5c0f30e-dc49-411d-a168-4d334e56bbc1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2c72f916-6890-494d-860f-24914d839be6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
