# Generated by Django 3.1.4 on 2022-08-26 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0005_auto_20220826_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleandatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4175fe12-2553-4b5d-85c2-4587e8e6b163'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3da354d3-88a8-4e8d-83aa-0a23d2c1f95a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
