# Generated by Django 3.1.4 on 2022-08-26 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0007_auto_20220826_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleandatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('baaaecc4-2013-4881-9dd1-68b16febaa60'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
