# Generated by Django 3.1.4 on 2022-08-26 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0008_auto_20220826_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleandatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac3c0cd4-47ae-4318-b409-3a08cafa3546'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
