# Generated by Django 3.1.4 on 2022-08-26 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0009_auto_20220826_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleandatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8f9c9ab-ef9a-4893-acab-6d63ea6d0608'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a272f7f2-3ec0-4dde-819d-0a7b1d7b304b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
