# Generated by Django 3.1.4 on 2022-08-26 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0010_auto_20220826_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0cbf0228-4191-4488-99b7-c2deb1467f58'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='sendCleanDataModel',
        ),
    ]
