# Generated by Django 3.1.4 on 2022-08-26 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0011_auto_20220826_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8b84125-614a-40d2-9f10-6fefcdfdac57'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
