# Generated by Django 3.1.4 on 2022-08-29 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0012_auto_20220826_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9c6bd614-a63b-457f-8f1b-6355c3622ef5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
