# Generated by Django 3.1.4 on 2022-08-30 17:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0013_auto_20220829_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('76b66782-d78f-411e-a0dc-e0ee0e6ac63a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
