# Generated by Django 3.1.4 on 2022-09-05 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0014_auto_20220830_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7285f639-d9db-428c-858d-adfb36a43cbb'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
