# Generated by Django 3.1.4 on 2022-09-06 16:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0015_auto_20220905_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('74eb8715-66e5-43c3-95a3-bb079ccdf0ef'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
