# Generated by Django 3.1.4 on 2022-09-06 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0016_auto_20220906_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e7c2417-0163-40b1-9597-64a04494edfe'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
