# Generated by Django 3.1.4 on 2022-09-06 16:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0017_auto_20220906_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('09ed90af-4e5f-4930-962b-17b0bcd7a575'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
