# Generated by Django 3.1.4 on 2022-09-07 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0018_auto_20220906_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a88dae5-6fab-47c3-9138-e44e7f2f25b3'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
