# Generated by Django 3.1.4 on 2022-09-14 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0019_auto_20220907_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('937a677e-26a6-4105-a60b-f3ca63f856bf'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
