# Generated by Django 3.1.4 on 2022-09-19 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0020_auto_20220914_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('192db7db-743e-4ec9-8db1-5736c1f93a96'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
