# Generated by Django 3.1.4 on 2022-09-27 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0021_auto_20220919_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('24796029-cca5-4741-94f8-a040f8f5a127'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
