# Generated by Django 3.1.4 on 2022-10-12 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0023_auto_20221012_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e5accbb0-14c3-4f00-a77c-2962208785b1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
