# Generated by Django 3.1.4 on 2022-10-12 17:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0024_auto_20221012_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('38d8e9e1-b90b-47bd-b2df-62218279c6a4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
