# Generated by Django 3.1.4 on 2022-10-12 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0025_auto_20221012_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('69dc6e05-e466-4c30-a6e9-afa54eaeea01'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
