# Generated by Django 3.1.4 on 2022-10-12 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0026_auto_20221012_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a6ec646b-69be-4ba3-a671-07dd184594ad'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
