# Generated by Django 3.1.4 on 2022-10-12 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0027_auto_20221012_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc16dceb-14bf-4214-8789-1a81626cb497'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
