# Generated by Django 3.1.4 on 2022-11-14 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0029_auto_20221012_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('88960380-8dc9-4f9c-a24b-5bea08a6ef6f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
