# Generated by Django 3.1.4 on 2022-12-15 17:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0031_auto_20221115_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8870e5f9-3c39-44b1-acfb-9c1df3493e2a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
