# Generated by Django 3.1.4 on 2022-12-18 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0032_auto_20221215_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b9c3a17d-79c9-42e6-9dd8-8f30e1927ae4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
