# Generated by Django 3.1.4 on 2022-12-20 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedulers', '0034_auto_20221218_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('efb5c044-1767-4bf6-84f3-4470e34f5235'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='RecruiterCallsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('recruiter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attempted_calls', models.CharField(blank=True, max_length=255, null=True)),
                ('connected_calls', models.CharField(blank=True, max_length=255, null=True)),
                ('missed_calls', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitercallsmodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recruitercallsmodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruiter_calls',
            },
        ),
    ]
