# Generated by Django 3.1.4 on 2022-12-20 11:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0035_auto_20221220_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd0e43e6-5c5c-4b85-999f-ba92591dabc0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
