# Generated by Django 3.1.4 on 2022-12-20 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0036_auto_20221220_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitercallsmodel',
            name='call_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a4e83901-1398-4fb1-b8f5-4ba89448a679'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
