# Generated by Django 3.1.4 on 2023-01-04 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0037_auto_20221220_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1e79b6e6-e871-414d-ade1-424b55f139c0'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
