# Generated by Django 3.1.4 on 2023-01-09 12:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0038_auto_20230104_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94a01aac-2ac8-4b99-9e29-1110389c0b3e'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
