# Generated by Django 3.1.4 on 2023-01-18 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0040_auto_20230111_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b028c3f1-fd25-43fa-850e-3fca528314ae'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
