# Generated by Django 3.1.4 on 2023-01-30 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedulers', '0041_auto_20230118_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cfd8692e-b1af-435c-aea1-5e6880b3fa48'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='AgentCallsDataModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('b041f231-51d6-46eb-a456-877601f48761'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('call_to_number', models.CharField(blank=True, max_length=255, null=True)),
                ('caller_id_number', models.CharField(blank=True, max_length=255, null=True)),
                ('start_stamp', models.CharField(blank=True, max_length=255, null=True)),
                ('answer_agent_number', models.CharField(blank=True, max_length=255, null=True)),
                ('call_id', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_circle', models.CharField(blank=True, max_length=255, null=True)),
                ('call_status', models.CharField(blank=True, max_length=255, null=True)),
                ('direction', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_no_with_prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentcallsdatamodel_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agentcallsdatamodel_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruiter_daily_calls',
            },
        ),
    ]
