# Generated by Django 3.1.4 on 2023-02-01 10:42

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0042_auto_20230130_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcallsdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f40f4219-6a0a-4be0-b5b6-2cf0365bd9ed'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='agentcallsdatamodel',
            name='start_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94937298-55c6-4afe-9eb9-532018552fe6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
