# Generated by Django 3.1.4 on 2023-02-02 10:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0044_auto_20230201_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcallsdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d0a1ba52-1a06-4f58-9976-175d9841304c'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
