# Generated by Django 3.1.4 on 2023-07-14 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0045_auto_20230202_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1d4ab19-58da-448b-a85b-0bf3c429e5b5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
