# Generated by Django 3.1.4 on 2023-07-17 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0046_auto_20230714_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8bf68605-319d-49d6-9f3c-f427d51059b7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
