# Generated by Django 3.1.4 on 2023-08-01 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0047_auto_20230717_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e9e45fe6-b8b6-4ae4-a0e9-dbba2b66a2d5'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
