# Generated by Django 3.1.4 on 2023-08-01 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0048_auto_20230801_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d6049ccc-3b35-4b25-9cdb-fb20ec45e327'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
