# Generated by Django 3.1.4 on 2023-08-01 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0049_auto_20230801_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9918854b-e6b9-42ea-ae5d-2cad5a07765a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
