# Generated by Django 3.1.4 on 2023-08-02 17:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0051_auto_20230802_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64e92a10-10c2-4f5e-9d42-31061ded6a52'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
