# Generated by Django 3.1.4 on 2023-08-04 10:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0052_auto_20230802_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f08d4f5f-ba69-43a7-868c-ff5827131283'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
