# Generated by Django 3.1.4 on 2023-08-04 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0053_auto_20230804_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('114f9be9-96c3-456b-9d03-dbfd70337595'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
