# Generated by Django 3.1.4 on 2023-08-07 09:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedulers', '0054_auto_20230804_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendcleanrequestdatamodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa851f62-5737-4bca-8c16-8c34e33c1b00'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
